# Generated by Django 2.2.12 on 2020-06-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poesie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poeme', models.FileField(upload_to='poeme/poesie')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Poésie',
                'verbose_name_plural': 'Poésies',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Présentation',
                'verbose_name_plural': 'Présentations',
            },
        ),
        migrations.CreateModel(
            name='TypeOeuvre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'oeuvre",
                'verbose_name_plural': "Types d'oeuvres",
            },
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeuvre', models.FileField(upload_to='oeuvre/oeuvre')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('type_oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvre_type', to='oeuvre.TypeOeuvre')),
            ],
            options={
                'verbose_name': 'oeuvre',
                'verbose_name_plural': 'oeuvres',
            },
        ),
    ]
