# Generated by Django 2.2.12 on 2020-06-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
