# Generated by Django 2.2.12 on 2020-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0002_remove_publication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Commentaire',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
