# Generated by Django 2.2.12 on 2020-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0003_auto_20200628_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
