# Generated by Django 2.2.12 on 2020-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0004_auto_20200628_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reponsecommentaire',
            options={'verbose_name': 'Reponse Commentaire', 'verbose_name_plural': 'Reponses Commentaires'},
        ),
        migrations.AddField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
