# Generated by Django 2.2.12 on 2020-06-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0005_auto_20200629_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='slug',
        ),
    ]
