# Generated by Django 2.2.12 on 2020-06-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0010_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
