# Generated by Django 2.2.12 on 2020-06-30 21:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0011_evenement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
