# Generated by Django 2.2.12 on 2020-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0012_auto_20200630_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='cours/pdf.png', upload_to='textes/image')),
                ('pdf', models.FileField(null=True, upload_to='pdf/textes')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Texte de référence',
                'verbose_name_plural': 'Textes de références ',
            },
        ),
    ]
