# Generated by Django 2.2.12 on 2020-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0016_auto_20200701_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsecommentaire',
            name='commentaires',
        ),
        migrations.AddField(
            model_name='reponsecommentaire',
            name='reponse',
            field=models.TextField(null=True),
        ),
    ]
