# Generated by Django 2.2.12 on 2020-06-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
