# Generated by Django 2.2.12 on 2020-06-29 13:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_gallerie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
